spring.application.name=sepa-importer

# Server
server.port=8080

# Datenbank
spring.datasource.url=jdbc:sqlserver://win2016-rch:1433;databaseName=ALL_dipsBANKING_MASTER;encrypt=true;trustServerCertificate=true;
spring.datasource.username=dips-1r
spring.datasource.password=dips-1R
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# HikariCP Connection Pool
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000

# Batch
spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=never
spring.batch.jdbc.table-prefix=batch.BATCH_

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# File Upload
spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=2GB
spring.servlet.multipart.location=./uploads/

# Logging
logging.level.org.springframework.batch=INFO
logging.level.com.sps.ids.swift_importer=DEBUG

# Actuator Endpoints (Spring Boot 3.x - keine individuelle Enable-Konfiguration nötig)
management.endpoints.web.exposure.include=batch,health,info,metrics,prometheus
management.endpoint.health.show-details=always

# Swift Import Path
#
# override via job-param
#
# POST /api/jobs/import-sepa
# {
# "filePath": "C:/data/STRUCTURES-SEPAD-V1-F-2026-02-01.xml"
# }

swift.import.filePath=D:/dev/java/spring/swift-importer/src/test/resources/samples/CALENDARS-CTRY-V1-F-2026-03-27.xml

# Jackson configuration
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss
spring.jackson.serialization.write-dates-as-timestamps=false