/* =======================================================================
   CREATE SCHEMA
   ======================================================================= */

IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'batch')
EXEC('CREATE SCHEMA batch');
GO

/* =======================================================================
   1) SEQUENCES
   ======================================================================= */

CREATE SEQUENCE batch.BATCH_JOB_SEQ
    START WITH 1
    INCREMENT BY 1;
GO

CREATE SEQUENCE batch.BATCH_JOB_EXECUTION_SEQ
    START WITH 1
    INCREMENT BY 1;
GO

CREATE SEQUENCE batch.BATCH_STEP_EXECUTION_SEQ
    START WITH 1
    INCREMENT BY 1;
GO

/* =======================================================================
   2) TABLES
   ======================================================================= */

CREATE TABLE batch.BATCH_JOB_INSTANCE  (
   JOB_INSTANCE_ID BIGINT NOT NULL PRIMARY KEY,
   VERSION BIGINT,
   JOB_NAME NVARCHAR(100) NOT NULL,
   JOB_KEY NVARCHAR(32) NOT NULL,
   CONSTRAINT BATCH_JOB_INST_UN UNIQUE (JOB_NAME, JOB_KEY)
);
GO

CREATE TABLE batch.BATCH_JOB_EXECUTION  (
    JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
    VERSION BIGINT,
    JOB_INSTANCE_ID BIGINT NOT NULL,
    CREATE_TIME DATETIME2 NOT NULL,
    START_TIME DATETIME2,
    END_TIME DATETIME2,
    STATUS NVARCHAR(10),
    EXIT_CODE NVARCHAR(2500),
    EXIT_MESSAGE NVARCHAR(2500),
    LAST_UPDATED DATETIME2,
    CONSTRAINT BATCH_JOB_EXEC_INST_FK
        FOREIGN KEY (JOB_INSTANCE_ID)
            REFERENCES batch.BATCH_JOB_INSTANCE(JOB_INSTANCE_ID)
);
GO

CREATE TABLE batch.BATCH_JOB_EXECUTION_PARAMS  (
   JOB_EXECUTION_ID BIGINT NOT NULL,
   PARAMETER_NAME NVARCHAR(100) NOT NULL,
   PARAMETER_TYPE NVARCHAR(100) NOT NULL,
   PARAMETER_VALUE NVARCHAR(2500),
   IDENTIFYING CHAR(1) NOT NULL,
   CONSTRAINT BATCH_JOB_EXEC_PARAMS_FK
       FOREIGN KEY (JOB_EXECUTION_ID)
           REFERENCES batch.BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
);
GO

CREATE TABLE batch.BATCH_STEP_EXECUTION  (
     STEP_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
     VERSION BIGINT NOT NULL,
     STEP_NAME NVARCHAR(100) NOT NULL,
     JOB_EXECUTION_ID BIGINT NOT NULL,
     CREATE_TIME DATETIME2 NOT NULL,
     START_TIME DATETIME2,
     END_TIME DATETIME2,
     STATUS NVARCHAR(10),
     COMMIT_COUNT BIGINT,
     READ_COUNT BIGINT,
     FILTER_COUNT BIGINT,
     WRITE_COUNT BIGINT,
     READ_SKIP_COUNT BIGINT,
     WRITE_SKIP_COUNT BIGINT,
     PROCESS_SKIP_COUNT BIGINT,
     ROLLBACK_COUNT BIGINT,
     EXIT_CODE NVARCHAR(2500),
     EXIT_MESSAGE NVARCHAR(2500),
     LAST_UPDATED DATETIME2,
     CONSTRAINT BATCH_STEP_EXEC_JOB_FK
         FOREIGN KEY (JOB_EXECUTION_ID)
             REFERENCES batch.BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
);
GO

CREATE TABLE batch.BATCH_JOB_EXECUTION_CONTEXT  (
    JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
    SHORT_CONTEXT NVARCHAR(2500),
    SERIALIZED_CONTEXT NVARCHAR(MAX),
    CONSTRAINT BATCH_JOB_EXEC_CTX_FK
        FOREIGN KEY (JOB_EXECUTION_ID)
            REFERENCES batch.BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
);
GO

CREATE TABLE batch.BATCH_STEP_EXECUTION_CONTEXT  (
     STEP_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
     SHORT_CONTEXT NVARCHAR(2500),
     SERIALIZED_CONTEXT NVARCHAR(MAX),
     CONSTRAINT BATCH_STEP_EXEC_CTX_FK
         FOREIGN KEY (STEP_EXECUTION_ID)
             REFERENCES batch.BATCH_STEP_EXECUTION(STEP_EXECUTION_ID)
);
GO
